import nbformat as nbf
import json
import os

try:
    import google.generativeai as genai
    HAS_GENAI = True
except ImportError:
    genai = None
    HAS_GENAI = False

class NotebookTools:

    def __init__(self):
        pass

    def _generate_gemini_insights(self, eda_output, model_output):
        """
        Creates AI-generated insights to embed inside the notebook.
        """
        if not HAS_GENAI:
            return "ℹ️ google-generativeai package not installed. Set up package and GEMINI_API_KEY to generate AI insights."

        try:
            api_key = os.environ.get("GOOGLE_API_KEY") or os.environ.get("GEMINI_API_KEY")

            if not api_key:
                return "ℹ️ Gemini API key not found. Set GEMINI_API_KEY to generate automated AI insights."

            genai.configure(api_key=api_key)
            model = genai.GenerativeModel("gemini-2.0-flash")

            prompt = f"""
            You are a senior ML engineer generating insights for a professional ML report.

            Write:
            1. Key Data Findings from EDA & Preprocessing
            2. Model Strengths & Weaknesses (including cross-validation stability)
            3. Most Important Features & Interpretability
            4. Suggested Next Steps & Risk Factors

            Use the following JSON:
            EDA: {json.dumps(eda_output, indent=2)}
            MODEL: {json.dumps(model_output, indent=2)}
            """

            resp = model.generate_content(prompt)
            return resp.text

        except Exception as e:
            return f"Gemini error: {str(e)}"

    def create_notebook(self, inputs):
        """
        inputs = {
            "profiler": {...},
            "eda": {...},
            "model": {...},
            "verifier": {...}
        }
        """
        nb = nbf.v4.new_notebook()
        cells = []

        # -------------------------------
        # TITLE PAGE
        # -------------------------------
        cells.append(nbf.v4.new_markdown_cell("# 📘 Auto-Generated Data Analysis Report"))
        cells.append(nbf.v4.new_markdown_cell("Generated by **Multi-Agent System + AutoML + Gemini AI**"))

        # -------------------------------
        # STRUCTURED AUTOML SECTIONS (IF PRESENT)
        # -------------------------------
        model_out = inputs.get("model", {})
        if isinstance(model_out, dict) and model_out.get("status") == "success":
            # Feature Engineering section
            fe = model_out.get("feature_engineering", {})
            outliers = model_out.get("outliers", {})
            fs = model_out.get("feature_selection", {})
            cv = model_out.get("cross_validation", {})
            fi = model_out.get("feature_importance", [])

            fe_md = "## ⚙️ Automated Feature Engineering & Outlier Analysis\n"
            if outliers:
                fe_md += f"- **Outlier Detection Method**: `{outliers.get('method', 'IQR')}`\n"
                fe_md += f"- **Total Outliers Detected**: `{outliers.get('total_outliers', 0)}` ({outliers.get('percentage_affected', 0)}% of rows affected)\n"
                fe_md += f"- **Handling Strategy**: `{outliers.get('handling_strategy', 'clip')}`\n\n"

            if fe:
                fe_md += f"- **Created Features**: {', '.join(fe.get('created_features', [])) or 'None'}\n"
                fe_md += f"- **Transformed Features**: {', '.join(fe.get('transformed_features', [])) or 'None'}\n"
                fe_md += f"- **Transformations Applied**: {', '.join(fe.get('transformations_applied', []))}\n\n"

            if fs:
                fe_md += f"- **Feature Selection**: Reduced from `{fs.get('original_count', 0)}` to `{fs.get('selected_count', 0)}` features using `{fs.get('method', 'k_best')}`\n"

            cells.append(nbf.v4.new_markdown_cell(fe_md))

            # Cross validation section
            if cv and "models" in cv:
                cv_md = "## 📊 Cross-Validation Performance\n\n"
                cv_md += "| Model | Mean CV Score | Std Dev | Fold Scores |\n"
                cv_md += "|---|---|---|---|\n"
                for m_name, m_info in cv["models"].items():
                    folds_str = ", ".join(str(s) for s in m_info.get("fold_scores", []))
                    cv_md += f"| **{m_name}** | {m_info.get('mean_cv_score', 'N/A')} | ±{m_info.get('std_cv_score', 'N/A')} | [{folds_str}] |\n"
                cells.append(nbf.v4.new_markdown_cell(cv_md))

            # Feature importance table
            if fi:
                fi_md = "## 🌟 Feature Importance Analysis\n\n"
                fi_md += "| Rank | Feature | Importance | Direction |\n"
                fi_md += "|---|---|---|---|\n"
                for item in fi[:10]:
                    fi_md += f"| {item.get('rank')} | `{item.get('feature')}` | {item.get('importance')} | {item.get('direction', 'N/A')} |\n"
                cells.append(nbf.v4.new_markdown_cell(fi_md))

        # -------------------------------
        # RAW INPUT SECTIONS
        # -------------------------------
        for section, value in inputs.items():
            cells.append(
                nbf.v4.new_markdown_cell(f"## 🔍 {section.upper()} Output\n```json\n{json.dumps(value, indent=2)}\n```")
            )

        # -------------------------------
        # GEMINI ANALYSIS SECTION
        # -------------------------------
        gemini_insights = self._generate_gemini_insights(
            eda_output=inputs.get("eda", {}),
            model_output=inputs.get("model", {})
        )

        cells.append(
            nbf.v4.new_markdown_cell(
                "## 🔮 Gemini AI Insights\n" +
                gemini_insights
            )
        )

        # -------------------------------
        # FINALIZE
        # -------------------------------
        nb["cells"] = cells
        nb_bytes = nbf.writes(nb).encode("utf-8")
        return nb_bytes
